/**:
  ros__parameters:
    host_ip: 192.168.1.101
    sensor_ip: 192.168.1.201
    data_port: 2368
    gnss_port: 2369
    launch_hw: true
    frame_id: robosense
    diag_span: 1000
    scan_phase: 0.0
    dual_return_distance_threshold: 0.1
    sensor_model: Bpearl
    return_mode: Strongest
    use_sensor_time: false
